CREATE DATABASE hero;

\c hero;

CREATE TABLE heros(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    heroName VARCHAR,
    heroAge INT,
    heroPower VARCHAR,
    heroWeakness VARCHAR,
    squadId INT,
    avatarUrl VARCHAR
);

CREATE TABLE squads (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    squadName VARCHAR,
    squadCause VARCHAR,
    maxSize INT,
    squadFull BOOLEAN
);

CREATE DATABASE hero_test WITH TEMPLATE hero;
